spring.application.name=homerecipeorganizer
spring.datasource.url=jdbc:postgresql://localhost:5433/YOUR DB
spring.datasource.username=YOUR USERNAME
spring.datasource.password=YOUR PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
testing.app.secret= YOUR SECRET
testing.app.lifeTime=3600000
server.port=8080
server.servlet.context-path=/api
