spring.application.name=homerecipeorganizer
spring.datasource.url=jdbc:postgresql://localhost:5433/HRO
spring.datasource.username=postgres
spring.datasource.password=111
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
testing.app.secret=ghbdtnvtyzpjdenve;fz;bdfyglrhtdtbreh.vf[jhreclhepmzvbxnjtotvjlyjmbfhdksdfsqqwweddffgdsfds!fdre%
testing.app.lifeTime=3600000
server.port=8080
server.servlet.context-path=/api